name: CI

on:
  push:
    branches:
      - main
      - '[0-9]+.[0-9]+.x'
    tags:
      - '[0-9]+.[0-9]+.[0-9]+'
      - '[0-9]+.[0-9]+.[0-9]+-next.[0-9]+'
      - '[0-9]+.[0-9]+.[0-9]+-rc.[0-9]+'
env:
  CI: 'true'

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

permissions: {}

defaults:
  run:
    shell: bash

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8 # v5.0.0
        with:
          filter: blob:none
          persist-credentials: false
      - name: Setup pnpm
        uses: pnpm/action-setup@a7487c7e89a18df4991f7f222e4898a00d66ddda # v4.1.0
        with:
          run_install: false
      - name: Setup Node.js
        uses: actions/setup-node@a0853c24544627f65ddf259abe73b1d18a591444 # v5.0.0
      - run: pnpm install --frozen-lockfile
      - name: Lint
        run: pnpm -s lint
      - name: Build
        run: pnpm -s build
      - name: Run tests
        run: pnpm -s test:specs
      - name: Run integration samples
        run: pnpm -s integration:samples
      - name: Run integration specs
        run: pnpm -s integration:specs
      - name: Run integration watch specs
        run: pnpm -s integration:watch:specs
      - name: Run integration consumers
        run: pnpm -s integration:consumers

  build-and-test-windows:
    runs-on: windows-2025
    steps:
      - uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8 # v5.0.0
        with:
          filter: blob:none
          persist-credentials: false
      - name: Setup pnpm
        uses: pnpm/action-setup@a7487c7e89a18df4991f7f222e4898a00d66ddda # v4.1.0
        with:
          run_install: false
      - name: Setup Node.js
        uses: actions/setup-node@a0853c24544627f65ddf259abe73b1d18a591444 # v5.0.0
      - run: pnpm install --frozen-lockfile
      - name: Build
        run: pnpm -s build
      - name: Run tests
        run: pnpm -s test:specs
      - name: Run integration samples
        run: pnpm -s integration:samples
      - name: Run integration specs
        run: pnpm -s integration:specs

  deploy:
    runs-on: ubuntu-latest
    needs: build-and-test
    environment: release
    if: startsWith(github.ref, 'refs/tags/')
    steps:
      - uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8 # v5.0.0
        with:
          filter: blob:none
          persist-credentials: false
      - name: Setup pnpm
        uses: pnpm/action-setup@a7487c7e89a18df4991f7f222e4898a00d66ddda # v4.1.0
        with:
          run_install: false
      - name: Setup Node.js
        uses: actions/setup-node@a0853c24544627f65ddf259abe73b1d18a591444 # v5.0.0
      - run: pnpm install --frozen-lockfile
      - name: Determine npm tag
        id: npm_tag
        run: |
          GIT_TAG=${{ github.ref_name }}
          NPM_TAG=latest
          if [[ "${GIT_TAG}" =~ ([0-9]+)\.([0-9]+)\.([0-9]+)-([a-zA-Z]+)\..* ]]; then
            NPM_TAG=next
          fi
          echo "NPM_TAG=$NPM_TAG" >> $GITHUB_OUTPUT
      - name: Configure NPM authentication
        run: pnpm config set '//registry.npmjs.org/:_authToken' "${NODE_AUTH_TOKEN}"
        env:
          NODE_AUTH_TOKEN: ${{secrets.NPM_TOKEN}}
      - name: Publish to NPM
        run: |
          pnpm -s publish:ci
          pushd dist
          pnpm publish --no-git-checks --access public --tag ${{ steps.npm_tag.outputs.NPM_TAG }}
